### ISSUE TITLE
errno: 150 "Foreign key constraint is incorrectly formed")

### ISSUE THREAD

**Issue by amitpammu** [nicolascava/sequelize-i18n#1]
Unhandled rejection SequelizeDatabaseError: Can't create table `dev_test`.`product_i18ns` (errno: 150 "Foreign key constraint is incorrectly formed")
    at Query.formatError (C:\Users\***\learnings\node\test-acl\node_modules\sequelize\lib\dialects\mysql\query.js:247:16)
    at Query.handler [as onResult] (C:\Users\****\learnings\node\test-acl\node_modules\sequelize\lib\dialects\mysql\query.js:68:23)
    at Query.Command.execute (C:\Users\****\learnings\node\test-acl\node_modules\mysql2\lib\commands\command.js:30:12)
    at Connection.handlePacket (C:\Users\***\learnings\node\test-acl\node_modules\mysql2\lib\connection.js:502:28)
    at PacketParser.onPacket (C:\Users\****\learnings\node\test-acl\node_modules\mysql2\lib\connection.js:81:16)
    at PacketParser.executeStart (C:\Users\***\learnings\node\test-acl\node_modules\mysql2\lib\packet_parser.js:77:14)
    at Socket.<anonymous> (C:\Users\***\learnings\node\test-acl\node_modules\mysql2\lib\connection.js:89:29)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onread (net.js:638:20)

**Comment by nicolascava** [comment]
I'm sorry, but I close this issue because it's old and probably not relevant anymore.
